Fix/update django
plus-me/backend pull request #5
Opened 2021-07-19 18:21 UTC by ri0t

There may still lurk problems deep down in some things.

2021-07-20 07:55 UTC, enko requested changes

2021-07-20 07:55 UTC, enko commented on wp_party/models.py
> +    id = models.SmallAutoField(primary_key=True)
Wieso hier `SmallAutoField`? Bei den anderen hast du überall `BigAutoField` benutzt?

2021-07-22 17:11 UTC, ri0t commented on wp_party/models.py
> +    id = models.SmallAutoField(primary_key=True)
32768 Parteien sollten ausreichen - bei den Tags würde das sicher auch tun, bei den anderen Feldern eher nicht.

2021-07-23 15:45 UTC, ri0t commented on wp_party/models.py
> +    id = models.SmallAutoField(primary_key=True)
Über die AutoFields können wir uns gerne nochmal unterhalten, ich resolve das jetzt erstmal.

2021-07-23 15:49 UTC, merged